[project]
name = "crystal-index"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.3",
]

[dependency-groups]
gui = [
        "opencv-python>=4.10.0.84",
]
